const blacklist = [
    'yuoia.com',
    'uzxia.com',
    'jontra.com',
    'gienig.com',
    'cwtaa.com',
    'dusyum.com',
    'baddomain.com',
    'nezid.com',
    'omeie.com',
    'zbock.com',
    'zslsz.com',
    'cazlq.com',
    'armyspy.com',
    'cuvox.de',
    'einrot.com',
    'fleckens.hu',
    'gustr.com',
    'jourrapide.com',
    'rhyta.com',
    'superrito.com',
    'teleworm.us',
    'holis.com',
    'example.com',
];

export default blacklist;